/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gubatron.maracucho;

import com.gubatron.maracucho.messages.HelloMessage;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class HelloMessageTest {
    @Test public void testHelloMessageAttributes() {
        HelloMessage hello = new HelloMessage();
        assertTrue("Hello message type should be 'hello'", hello.type.equals("hello"));
        assertTrue("Hello message version should be " + Constants.VERSION, hello.version.equals(Constants.VERSION));
        assertTrue("Agent should be '" + Constants.AGENT + "'", hello.agent.equals(Constants.AGENT));
    }
}
