/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gubatron.maracucho.messages;

public class Message {
    public final String type;
    public Message(String _type) {
        type = _type;
    }
}
